---
name: 'SOUP'
description: 'Execute soup'

inputs:
  ssh-key:
    description: 'ssh key'
    required: true
  github-token:
    description: 'github token'
    required: false
    default: ''
  parameters:
    description: 'soup parameters'
    required: false
    default: '--no_prompt'

runs:
  using: "composite"
  steps:
    # https://github.com/marketplace/actions/checkout
    - uses: actions/checkout@v4
      with:
        ssh-key: ${{ inputs.ssh-key }}
        persist-credentials: true
        lfs: true
        submodules: recursive

    # https://github.com/Cloud-Officer/soup
    - shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        latest_tag="$(curl --silent https://api.github.com/repos/Cloud-Officer/soup/tags | jq -r '.[0].name')"
        echo "Latest soup tag: ${latest_tag}"
        asset_url=""https://github.com/Cloud-Officer/soup/archive/refs/tags/${latest_tag}.zip""
        curl -L "${asset_url}" -o "${RUNNER_TEMP}/soup.zip"
        unzip -q "${RUNNER_TEMP}/soup.zip" -d "${RUNNER_TEMP}"
        rm -rf "${RUNNER_TEMP}/soup.zip"
        pushd "${RUNNER_TEMP}"
        bundle install
        popd
        "${RUNNER_TEMP}/bin/soup.rb" ${{ inputs.parameters }}
