---
name: 'SOUP'
description: 'Execute soup'

inputs:
  ssh-key:
    description: 'ssh key'
    required: true
  github-token:
    description: 'github token'
    required: false
    default: ${{ github.token }}
  parameters:
    description: 'soup parameters'
    required: false
    default: '--no_prompt'

runs:
  using: "composite"
  steps:
    # https://github.com/marketplace/actions/checkout
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ssh-key: ${{ inputs.ssh-key }}
        persist-credentials: true
        lfs: true
        submodules: recursive
        token: ${{ inputs.github-token }}

    - name: Get SOUP Code
      shell: bash
      id: soup
      run: |
        latest_tag="$(curl --silent --header "Authorization: Bearer ${{ inputs.github-token }}" https://api.github.com/repos/Cloud-Officer/soup/tags | jq -r '.[0].name')"
        echo "Latest soup tag: ${latest_tag}"
        asset_url=""https://github.com/Cloud-Officer/soup/archive/refs/tags/${latest_tag}.zip""
        curl -L "${asset_url}" -o "${RUNNER_TEMP}/soup.zip"
        unzip -q "${RUNNER_TEMP}/soup.zip" -d "${RUNNER_TEMP}"
        rm -rf "${RUNNER_TEMP}/soup.zip"
        echo "soup_location=${RUNNER_TEMP}/soup-${latest_tag}" >> ${GITHUB_ENV}

    # https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby
    - name: Setup Ruby
      uses: ruby/setup-ruby@master
      with:
        ruby-version: 3.3.6
        bundler: 'none'

    # https://github.com/Cloud-Officer/soup
    - name: Run SOUP
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      run: |
        pushd "${{env.soup_location}}"
        bundle config unset deployment
        bundle install
        popd
        "${{env.soup_location}}/bin/soup.rb" ${{ inputs.parameters }}
