---
name: 'Trivy'
description: 'Execute trivy'

inputs:
  linters:
    description: 'List of all enabled linters'
    required: true
  ssh-key:
    description: 'ssh key'
    required: true
  github-token:
    description: 'github token'
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - name: Check if TRIVY is enabled
      id: check
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        LINTERS: ${{ inputs.linters }}
      run: if echo "${LINTERS}" | grep TRIVY &> /dev/null; then echo "continue=true" >> "${GITHUB_OUTPUT}"; else echo "continue=false" >> "${GITHUB_OUTPUT}"; fi

    # https://github.com/marketplace/actions/checkout
    - name: Checkout
      uses: actions/checkout@v6
      if: ${{ steps.check.outputs.continue == 'true' }}
      with:
        token: ${{ inputs.github-token }}
        ssh-key: ${{ inputs.ssh-key }}
        persist-credentials: false
        lfs: true
        submodules: recursive

    - name: Detect Trivy scanners
      id: scanners
      shell: bash
      if: ${{ steps.check.outputs.continue == 'true' }}
      env:
        LINTERS: ${{ inputs.linters }}
      run: |
        scanners="secret"

        # Enable misconfig when IaC files are detected
        if echo "${LINTERS}" | grep -qE "CFNLINT|HADOLINT" || \
           find . -maxdepth 3 -name "*.tf" -print -quit 2>/dev/null | grep -q . || \
           find . -maxdepth 3 -name "Dockerfile*" -print -quit 2>/dev/null | grep -q .; then
          scanners="${scanners},misconfig"
        fi

        # Enable vuln when package manager lock files are detected
        for lock_file in package-lock.json yarn.lock pnpm-lock.yaml go.sum \
                         requirements.txt Pipfile.lock poetry.lock \
                         Gemfile.lock composer.lock \
                         pom.xml build.gradle build.gradle.kts \
                         Cargo.lock Package.resolved; do
          if [ -f "${lock_file}" ]; then
            scanners="${scanners},vuln"
            break
          fi
        done

        echo "scanners=${scanners}" >> "${GITHUB_OUTPUT}"
        echo "Trivy scanners: ${scanners}"

    # Install Trivy from deb repository (aquasecurity/trivy-repo)
    # setup-trivy cannot be used because aquasecurity/trivy repo was wiped on 2026-03-01
    - name: Install Trivy
      shell: bash
      if: ${{ steps.check.outputs.continue == 'true' }}
      run: |
        sudo apt-get install -y wget apt-transport-https gnupg
        wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null
        echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb noble main" | sudo tee /etc/apt/sources.list.d/trivy.list
        sudo apt-get update
        sudo apt-get install -y trivy

    # https://github.com/marketplace/actions/aqua-security-trivy
    - name: Run Trivy
      uses: aquasecurity/trivy-action@0.34.1
      if: ${{ steps.check.outputs.continue == 'true' }}
      with:
        scan-type: 'fs'
        scan-ref: '.'
        scanners: ${{ steps.scanners.outputs.scanners }}
        format: 'table'
        exit-code: '1'
        skip-setup-trivy: true
