---
name: 'Trivy'
description: 'Execute trivy'

inputs:
  linters:
    description: 'List of all enabled linters'
    required: true
  ssh-key:
    description: 'ssh key'
    required: true
  github-token:
    description: 'github token'
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - name: Check if TRIVY is enabled
      id: check
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        LINTERS: ${{ inputs.linters }}
      run: if echo "${LINTERS}" | grep TRIVY &> /dev/null; then echo "continue=true" >> "${GITHUB_OUTPUT}"; else echo "continue=false" >> "${GITHUB_OUTPUT}"; fi

    # https://github.com/marketplace/actions/checkout
    - name: Checkout
      uses: actions/checkout@v6
      if: ${{ steps.check.outputs.continue == 'true' }}
      with:
        token: ${{ inputs.github-token }}
        ssh-key: ${{ inputs.ssh-key }}
        persist-credentials: false
        lfs: true
        submodules: recursive

    # https://github.com/marketplace/actions/aqua-security-trivy
    - name: Run Trivy
      uses: aquasecurity/trivy-action@0.34.0
      if: ${{ steps.check.outputs.continue == 'true' }}
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'table'
        exit-code: '1'
