---
name: 'ShellCheck'
description: 'Execute shellcheck'

inputs:
  linters:
    description: 'List of all enabled linters'
    required: true
  ssh-key:
    description: 'ssh key'
    required: true
  github-token:
    description: 'github token'
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - name: Check if SHELLCHECK is enabled
      id: check
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        LINTERS: ${{ inputs.linters }}
      run: if echo "${LINTERS}" | grep SHELLCHECK &> /dev/null; then echo "continue=true" >> "${GITHUB_OUTPUT}"; else echo "continue=false" >> "${GITHUB_OUTPUT}"; fi

    # https://github.com/marketplace/actions/checkout
    - name: Checkout
      uses: actions/checkout@v6
      if: ${{ steps.check.outputs.continue == 'true' }}
      with:
        token: ${{ inputs.github-token }}
        ssh-key: ${{ inputs.ssh-key }}
        persist-credentials: false
        lfs: true
        submodules: recursive

    # https://github.com/marketplace/actions/run-shellcheck-with-reviewdog
    - name: Run Shellcheck with Reviewdog
      uses: reviewdog/action-shellcheck@v1
      if: ${{ steps.check.outputs.continue == 'true' }}
      with:
        exclude: "./.git/*"
        fail_level: any
        filter_mode: nofilter
        github_token: ${{ inputs.github-token }}
        level: info
        path: "."
        pattern: "*.sh"
        reporter: github-pr-review
        # reviewdog_flags:
        # https://github.com/koalaman/shellcheck
        shellcheck_flags: --external-sources
