---
name: 'Protolint'
description: 'Execute protolint'

inputs:
  linters:
    description: 'List of all enabled linters'
    required: true
  ssh-key:
    description: 'ssh key'
    required: true
  github-token:
    description: 'github token'
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - name: Check if PROTOLINT is enabled
      id: check
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        LINTERS: ${{ inputs.linters }}
      run: if echo "${LINTERS}" | grep PROTOLINT &> /dev/null; then echo "continue=true" >> "${GITHUB_OUTPUT}"; else echo "continue=false" >> "${GITHUB_OUTPUT}"; fi

    # https://github.com/marketplace/actions/checkout
    - name: Checkout
      uses: actions/checkout@v6
      if: ${{ steps.check.outputs.continue == 'true' }}
      with:
        token: ${{ inputs.github-token }}
        ssh-key: ${{ inputs.ssh-key }}
        persist-credentials: true
        lfs: true
        submodules: recursive

    # https://github.com/marketplace/actions/run-protolint-with-reviewdog
    - name: Run Protolint with Reviewdog
      uses: yoheimuta/action-protolint@v1
      if: ${{ steps.check.outputs.continue == 'true' }}
      with:
        # https://github.com/yoheimuta/protolint
        fail_level: any
        filter_mode: nofilter
        github_token: ${{ inputs.github-token }}
        level: info
        #protolint_version:
        protolint_flags: "."
        reporter: github-pr-review
        # reviewdog_flags:
