---
name: 'ESLint'
description: 'Execute eslint'

inputs:
  linters:
    description: 'List of all enabled linters'
    required: true
  ssh-key:
    description: 'ssh key'
    required: true
  github-token:
    description: 'github token'
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - id: check
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        LINTERS: ${{ inputs.linters }}
      run: if echo "${LINTERS}" | grep ESLINT &> /dev/null; then echo "continue=true" >> "${GITHUB_OUTPUT}"; else echo "continue=false" >> "${GITHUB_OUTPUT}"; fi

    # https://github.com/marketplace/actions/checkout
    - name: Checkout
      uses: actions/checkout@v6
      if: ${{ steps.check.outputs.continue == 'true' }}
      with:
        token: ${{ inputs.github-token }}
        ssh-key: ${{ inputs.ssh-key }}
        persist-credentials: false
        lfs: true
        submodules: recursive

    # https://github.com/marketplace/actions/setup-node-js-environment
    - name: Setup Node
      uses: actions/setup-node@v6
      if: ${{ steps.check.outputs.continue == 'true' }}
      with:
        token: ${{ inputs.github-token }}
        node-version: latest  # Intentionally using latest to always use newest Node.js

    - name: Install ESLint
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      if: ${{ steps.check.outputs.continue == 'true' }}
      run: npm install eslint@latest  # Intentionally using latest

    # https://github.com/marketplace/actions/run-eslint-with-reviewdog
    - name: Run ESLint with Reviewdog
      uses: reviewdog/action-eslint@v1
      if: ${{ steps.check.outputs.continue == 'true' }}
      with:
        # https://github.com/eslint/eslint
        eslint_flags: "."
        fail_level: any
        filter_mode: nofilter
        github_token: ${{ inputs.github-token }}
        level: info
        reporter: github-pr-review
        # reviewdog_flags:
        tool_name: eslint
        workdir: "."
