---
name: 'PHPCS'
description: 'Execute php-cs-fixer'

inputs:
  linters:
    description: 'List of all enabled linters'
    required: true
  ssh-key:
    description: 'ssh key'
    required: true
  github_token:
    description: 'github token'
    required: true
  php-version:
    description: 'php version'
    required: false
    default: '8.2'
  php-extensions:
    description: 'php extensions'
    required: false
    default: ''
  composer-command:
    description: 'composer command'
    required: false
    default: 'none'
  php-cs-fixer-version:
    description: 'php-cd-fixer version'
    required: false
    default: 'latest'
  php-cs-fixer-command:
    description: 'php-cs-fixer command(s)'
    required: false
    default: './php-cs-fixer fix --dry-run --diff --verbose'

runs:
  using: "composite"
  steps:
    - name: Check if PHPCS is enabled
      id: check
      shell: bash
      run: if echo "${{ inputs.linters }}" | grep PHPCS &> /dev/null; then echo "continue=true" >> "${GITHUB_OUTPUT}"; else echo "continue=false" >> "${GITHUB_OUTPUT}"; fi

    # https://github.com/marketplace/actions/checkout
    - name: Checkout
      uses: actions/checkout@v4
      if: ${{ steps.check.outputs.continue == 'true' }}
      with:
        ssh-key: ${{ inputs.ssh-key }}
        persist-credentials: true
        lfs: true
        submodules: recursive

    # https://github.com/marketplace/actions/setup-php-action
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      if: ${{ steps.check.outputs.continue == 'true' }}
      with:
        php-version: ${{ inputs.php-version }}
        extensions: ${{ inputs.php-extensions }}
        tools: composer

    - name: Setup php-cs-fixer
      shell: bash
      if: ${{ steps.check.outputs.continue == 'true' && inputs.composer-command == 'none'}}
      run: |
        if [ "${{ inputs.php-cs-fixer-version }}" == "latest" ] ;then
          curl -L https://cs.symfony.com/download/php-cs-fixer-v3.phar -o php-cs-fixer && chmod a+x php-cs-fixer
        else
          curl -L https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/${{ inputs.php-cs-fixer-version }}/php-cs-fixer.phar -o php-cs-fixer && chmod a+x php-cs-fixer
        fi

    - name: Run Composer
      shell: bash
      if: ${{ steps.check.outputs.continue == 'true' && inputs.composer-command != 'none'}}
      run: ${{ inputs.composer-command }}

    # https://cs.symfony.com/doc/usage.html
    - name: Run php-cs-fixer
      shell: bash
      if: ${{ steps.check.outputs.continue == 'true' }}
      run: ${{ inputs.php-cs-fixer-command }}
