---
name: 'PHPCS'
description: 'Execute php-cs-fixer'

inputs:
  linters:
    description: 'List of all enabled linters'
    required: true
  ssh-key:
    description: 'ssh key'
    required: true
  github_token:
    description: 'github token'
    required: true
  php-version:
    description: 'php version'
    required: false
    default: '7.4'
  php-cs-fixer-version:
    description: 'php-cd-fixer version'
    required: false
    default: 'latest'

runs:
  using: "composite"
  steps:
    - id: check
      shell: bash
      run: if echo "${{ inputs.linters }}" | grep PHPCS &> /dev/null; then echo "::set-output name=continue::true"; else echo "::set-output name=continue::false"; fi

    # https://github.com/marketplace/actions/checkout
    - uses: actions/checkout@v3
      if: ${{ steps.check.outputs.continue == 'true' }}
      with:
        ssh-key: ${{ inputs.ssh-key }}
        persist-credentials: true
        lfs: true
        submodules: recursive

    # https://github.com/marketplace/actions/setup-php-action
    - uses: shivammathur/setup-php@v2
      if: ${{ steps.check.outputs.continue == 'true' }}
      with:
        php-version: ${{ inputs.php-version }}
        tools: composer

    - shell: bash
      if: ${{ steps.check.outputs.continue == 'true' }}
      run: |
        if [ "${{ inputs.php-cs-fixer-version }}" == "latest" ] ;then
          curl -L https://cs.symfony.com/download/php-cs-fixer-v3.phar -o php-cs-fixer && chmod a+x php-cs-fixer
        else
          curl -L https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/${{ inputs.php-cs-fixer-version }}/php-cs-fixer.phar -o php-cs-fixer && chmod a+x php-cs-fixer
        fi

    # https://cs.symfony.com/doc/usage.html
    - shell: bash
      if: ${{ steps.check.outputs.continue == 'true' }}
      run: ./php-cs-fixer fix --dry-run --diff --verbose
