---
name: 'PHPCS'
description: 'Execute php-cs-fixer'

inputs:
  linters:
    description: 'List of all enabled linters'
    required: true
  ssh-key:
    description: 'ssh key'
    required: true
  github-token:
    description: 'github token'
    required: false
    default: ${{ github.token }}
  php-version:
    description: 'php version'
    required: false
    default: '8.2'
  php-extensions:
    description: 'php extensions'
    required: false
    default: ''
  composer-command:
    description: 'composer command'
    required: false
    default: 'none'
  php-cs-fixer-version:
    description: 'php-cd-fixer version'
    required: false
    default: 'latest'  # Intentionally using latest
  php-cs-fixer-command:
    description: 'php-cs-fixer command(s)'
    required: false
    default: './php-cs-fixer fix --dry-run --diff --verbose'

runs:
  using: "composite"
  steps:
    - name: Check if PHPCS is enabled
      id: check
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        LINTERS: ${{ inputs.linters }}
      run: if echo "${LINTERS}" | grep PHPCS &> /dev/null; then echo "continue=true" >> "${GITHUB_OUTPUT}"; else echo "continue=false" >> "${GITHUB_OUTPUT}"; fi

    # https://github.com/marketplace/actions/checkout
    - name: Checkout
      uses: actions/checkout@v6
      if: ${{ steps.check.outputs.continue == 'true' }}
      with:
        token: ${{ inputs.github-token }}
        ssh-key: ${{ inputs.ssh-key }}
        persist-credentials: false
        lfs: true
        submodules: recursive

    # https://github.com/marketplace/actions/setup-php-action
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      if: ${{ steps.check.outputs.continue == 'true' }}
      with:
        php-version: ${{ inputs.php-version }}
        extensions: ${{ inputs.php-extensions }}
        tools: composer

    - name: Setup php-cs-fixer
      shell: bash
      if: ${{ steps.check.outputs.continue == 'true' && inputs.composer-command == 'none'}}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        PHP_CS_FIXER_VERSION: ${{ inputs.php-cs-fixer-version }}
      run: |
        gpg --keyserver hkps://keyserver.ubuntu.com --recv-keys E82B2FB314E9906E
        if [ "${PHP_CS_FIXER_VERSION}" == "latest" ] ;then
          curl -L https://cs.symfony.com/download/php-cs-fixer-v3.phar -o php-cs-fixer
          curl -L https://cs.symfony.com/download/php-cs-fixer-v3.phar.asc -o php-cs-fixer.asc
        else
          curl -L "https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/${PHP_CS_FIXER_VERSION}/php-cs-fixer.phar" -o php-cs-fixer
          curl -L "https://github.com/FriendsOfPHP/PHP-CS-Fixer/releases/download/${PHP_CS_FIXER_VERSION}/php-cs-fixer.phar.asc" -o php-cs-fixer.asc
        fi
        gpg --verify php-cs-fixer.asc php-cs-fixer
        rm -f php-cs-fixer.asc
        chmod a+x php-cs-fixer

    - name: Run Composer
      shell: bash
      if: ${{ steps.check.outputs.continue == 'true' && inputs.composer-command != 'none'}}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        COMPOSER_COMMAND: ${{ inputs.composer-command }}
      run: eval "${COMPOSER_COMMAND}"

    # https://cs.symfony.com/doc/usage.html
    - name: Run php-cs-fixer
      shell: bash
      if: ${{ steps.check.outputs.continue == 'true' }}
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        PHP_CS_FIXER_COMMAND: ${{ inputs.php-cs-fixer-command }}
      run: eval "${PHP_CS_FIXER_COMMAND}"
