---
name: 'Snyk'
description: 'Execute snyk'

inputs:
  ssh-key:
    description: 'ssh key'
    required: true
  snyk-token:
    description: 'snyk token'
    required: true
  snyk-org:
    description: 'snyk org'
    required: true
  snyk-parameters:
    description: 'snyk parameters'
    required: fasle
    defaul: '--all-projects'

runs:
  using: "composite"
  steps:
    # https://github.com/marketplace/actions/checkout
    - uses: actions/checkout@v2
      with:
        ssh-key: ${{ inputs.ssh-key }}
        persist-credentials: true
        lfs: true
        submodules: recursive

    - shell: bash
      run: if ! which sha256sum &> /dev/null; then brew install coreutils ; fi

    # https://github.com/marketplace/actions/setup-go-environment
    - uses: actions/setup-go@v2
      with:
        go-version: '1.13'

    # https://support.snyk.io/hc/en-us/articles/360002118098-How-do-I-specify-a-custom-manifest-file-name-for-snyk-test-
    - shell: bash
      env:
        SNYK_TOKEN: ${{ inputs.snyk-token }}
      run: |
        "${GITHUB_ACTION_PATH}"/setup_snyk.sh latest ${{ runner.os }}
        snyk test --org=${{ inputs.snyk-org }} ${{ inputs.snyk-parameters }}
