---
name: 'Flake8'
description: 'Execute flake8'

inputs:
  linters:
    description: 'List of all enabled linters'
    required: true
  docstrings:
    description: 'Whether to lint docstrings or not'
    required: false
    default: false
    type: boolean
  ssh-key:
    description: 'ssh key'
    required: true
  github_token:
    description: 'github token'
    required: true

runs:
  using: "composite"
  steps:
    - id: check
      shell: bash
      run: if echo "${{ inputs.linters }}" | grep FLAKE8 &> /dev/null; then echo "::set-output name=continue::true"; else echo "::set-output name=continue::false"; fi

    # https://github.com/marketplace/actions/checkout
    - uses: actions/checkout@v2
      if: ${{ steps.check.outputs.continue == 'true' }}
      with:
        ssh-key: ${{ inputs.ssh-key }}
        persist-credentials: true
        lfs: true
        submodules: recursive

    # https://github.com/marketplace/actions/setup-reviewdog
    - uses: reviewdog/action-setup@v1
      if: ${{ steps.check.outputs.continue == 'true' }}
      with:
        reviewdog_version: latest

    - shell: bash
      run: pip install --upgrade flake8

    - shell: bash
      if: ${{ (steps.check.outputs.continue == 'true') && (inputs.docstrings == true) }}
      run: pip install --upgrade flake8-docstrings

    - shell: bash
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ inputs.github_token }}
      run: flake8 . "" 2>&1 | reviewdog -f=flake8 -name="flake8" -reporter="github-pr-review" -filter-mode="nofilter" -fail-on-error="true" -level="info" ""
