---
name: 'Rubocop'
description: 'Execute rubocop'

inputs:
  linters:
    description: 'List of all enabled linters'
    required: true
  ssh-key:
    description: 'ssh key'
    required: true
  github-token:
    description: 'github token'
    required: false
    default: ${{ github.token }}
  ruby-version:
    description: 'ruby version'
    required: false
    default: '4.0'

runs:
  using: "composite"
  steps:
    - name: Check if RUBOCOP is enabled
      id: check
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        LINTERS: ${{ inputs.linters }}
      run: if echo "${LINTERS}" | grep RUBOCOP &> /dev/null; then echo "continue=true" >> "${GITHUB_OUTPUT}"; else echo "continue=false" >> "${GITHUB_OUTPUT}"; fi

    # https://github.com/marketplace/actions/checkout
    - name: Checkout
      uses: actions/checkout@v6
      if: ${{ steps.check.outputs.continue == 'true' }}
      with:
        token: ${{ inputs.github-token }}
        ssh-key: ${{ inputs.ssh-key }}
        persist-credentials: true
        lfs: true
        submodules: recursive

    # https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      if: ${{ steps.check.outputs.continue == 'true' }}
      with:
        ruby-version: ${{ inputs.ruby-version }}

    # https://github.com/marketplace/actions/run-rubocop-with-reviewdog
    - name: Run Rubocop with Reviewdog
      uses: reviewdog/action-rubocop@v2
      if: ${{ steps.check.outputs.continue == 'true' }}
      with:
        fail_level: any
        filter_mode: nofilter
        github_token: ${{ inputs.github-token }}
        level: info
        reporter: github-pr-review
        # reviewdog_flags:
        rubocop_extensions: "rubocop-capybara rubocop-graphql rubocop-i18n rubocop-minitest rubocop-performance rubocop-rails rubocop-rake rubocop-rspec rubocop-rspec_rails rubocop-thread_safety"
        # https://rubocop.org/
        rubocop_flags: " --except Layout/LineLength,Metrics/BlockLength"
        # rubocop_version:
        tool_name: rubocop
        workdir: "."
