---
name: 'Actionlint'
description: 'Execute actionlint'

inputs:
  linters:
    description: 'List of all enabled linters'
    required: true
  ssh-key:
    description: 'ssh key'
    required: true
  github-token:
    description: 'github token'
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - id: check
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        LINTERS: ${{ inputs.linters }}
      run: if echo "${LINTERS}" | grep ACTIONLINT &> /dev/null; then echo "continue=true" >> "${GITHUB_OUTPUT}"; else echo "continue=false" >> "${GITHUB_OUTPUT}"; fi

    # https://github.com/marketplace/actions/checkout
    - name: Checkout
      uses: actions/checkout@v6
      if: ${{ steps.check.outputs.continue == 'true' }}
      with:
        token: ${{ inputs.github-token }}
        ssh-key: ${{ inputs.ssh-key }}
        persist-credentials: true
        lfs: true
        submodules: recursive

    # https://github.com/marketplace/actions/actionlint-with-reviewdog
    - name: Actionlint
      uses: reviewdog/action-actionlint@v1
      if: ${{ steps.check.outputs.continue == 'true' }}
      with:
        # https://github.com/rhysd/actionlint
        #actionlint_flags:
        fail_level: any
        filter_mode: nofilter
        github_token: ${{ inputs.github-token }}
        level: info
        reporter: github-pr-review
        # reviewdog_flags:
        tool_name: actionlint
