---
name: 'PMD'
description: 'Execute pmd'

inputs:
  linters:
    description: 'List of all enabled linters'
    required: true
  ssh-key:
    description: 'ssh key'
    required: true
  github-token:
    description: 'github token'
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - name: Check if PMD is enabled
      id: check
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        LINTERS: ${{ inputs.linters }}
      run: if echo "${LINTERS}" | grep PMD &> /dev/null; then echo "continue=true" >> "${GITHUB_OUTPUT}"; else echo "continue=false" >> "${GITHUB_OUTPUT}"; fi

    # https://github.com/marketplace/actions/checkout
    - name: Checkout
      uses: actions/checkout@v6
      if: ${{ steps.check.outputs.continue == 'true' }}
      with:
        token: ${{ inputs.github-token }}
        ssh-key: ${{ inputs.ssh-key }}
        persist-credentials: false
        lfs: true
        submodules: recursive

    # https://github.com/marketplace/actions/setup-reviewdog
    - name: Setup Reviewdog
      uses: reviewdog/action-setup@v1
      if: ${{ steps.check.outputs.continue == 'true' }}
      with:
        reviewdog_version: latest  # Intentionally using latest

    # https://github.com/marketplace/actions/setup-java-jdk
    - name: Setup Java
      uses: actions/setup-java@v5
      if: ${{ steps.check.outputs.continue == 'true' }}
      with:
        token: ${{ inputs.github-token }}
        distribution: temurin
        java-version: 21  # Intentionally using latest LTS
        check-latest: true

    - name: Setup PMD
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      if: ${{ steps.check.outputs.continue == 'true' }}
      run: |
        # Intentionally using latest - fetch latest release from GitHub API
        PMD_VERSION=$(curl --fail -s -H "Authorization: Bearer ${GITHUB_TOKEN}" https://api.github.com/repos/pmd/pmd/releases/latest | jq -r '.tag_name' | sed 's/pmd_releases\///')
        echo "Installing PMD version: ${PMD_VERSION}"
        wget -q -O /opt/pmd.zip "https://github.com/pmd/pmd/releases/download/pmd_releases%2F${PMD_VERSION}/pmd-dist-${PMD_VERSION}-bin.zip"
        wget -q -O /opt/pmd.zip.asc "https://github.com/pmd/pmd/releases/download/pmd_releases%2F${PMD_VERSION}/pmd-dist-${PMD_VERSION}-bin.zip.asc"
        gpg --keyserver hkps://keyserver.ubuntu.com --recv-keys 98313B2644E62EA447F7C58C08AACF8B0D441047
        gpg --verify /opt/pmd.zip.asc /opt/pmd.zip
        unzip -q -d /opt /opt/pmd.zip
        rm -f /opt/pmd.zip /opt/pmd.zip.asc
        mv /opt/pmd-bin-${PMD_VERSION} /opt/pmd
        chmod +x /opt/pmd/bin/*

    - name: Run PMD
      shell: bash
      if: ${{ steps.check.outputs.continue == 'true' }}
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ inputs.github-token }}
      run: /opt/pmd/bin/pmd check -d . -R ".pmd.xml" -f text | reviewdog -efm="%f:%l:%m" -name="linter-name (pmd)" -reporter="github-pr-review" -filter-mode="nofilter" -fail-level="any" -level="info"
