---
name: 'Checkout'
description: 'Checkout'

inputs:
  ssh-key:
    description: 'ssh key'
    required: true
runs:
  using: 'composite'
  steps:
    # https://github.com/marketplace/actions/checkout
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ssh-key: ${{ inputs.ssh-key }}
        persist-credentials: true
        lfs: true
        submodules: recursive
