---
name: 'S3Copy'
description: 'AWS S3 Copy'

inputs:
  github-token:
    description: 'github token'
    required: false
    default: ${{ github.token }}
  aws-access-key-id:
    description: 'aws access key id'
    required: true
  aws-secret-access-key:
    description: 'aws secret access key'
    required: true
  aws-region:
    description: 'aws region'
    required: true
  source:
    description: 'aws s3 sync source'
    required: true
  target:
    description: 'aws s3 sync target'
    required: true
runs:
  using: 'composite'
  steps:
    # https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v5
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - name: Sync S3
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        SOURCE: ${{ inputs.source }}
        TARGET: ${{ inputs.target }}
      run: aws s3 sync "${SOURCE}" "${TARGET}"
