---
name: 'Cfn-lint'
description: 'Execute cfn-lint'

inputs:
  linters:
    description: 'List of all enabled linters'
    required: true
  ssh-key:
    description: 'ssh key'
    required: true
  github-token:
    description: 'github token'
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - name: Check if CFNLINT is enabled
      id: check
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        LINTERS: ${{ inputs.linters }}
      run: if echo "${LINTERS}" | grep CFNLINT &> /dev/null; then echo "continue=true" >> "${GITHUB_OUTPUT}"; else echo "continue=false" >> "${GITHUB_OUTPUT}"; fi

    # https://github.com/marketplace/actions/checkout
    - name: Checkout
      uses: actions/checkout@v6
      if: ${{ steps.check.outputs.continue == 'true' }}
      with:
        token: ${{ inputs.github-token }}
        ssh-key: ${{ inputs.ssh-key }}
        persist-credentials: false
        lfs: true
        submodules: recursive

    # https://github.com/marketplace/actions/setup-reviewdog
    - name: Setup Reviewdog
      uses: reviewdog/action-setup@v1
      if: ${{ steps.check.outputs.continue == 'true' }}
      with:
        reviewdog_version: latest  # Intentionally using latest

    # cfn-lint
    - name: Install cfn-lint
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      if: ${{ steps.check.outputs.continue == 'true' }}
      run: |
        sudo rm -f /usr/lib/python3*/EXTERNALLY-MANAGED
        pip install --upgrade cfn-lint
    - name: Run cfn-lint
      shell: bash
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ inputs.github-token }}
      if: ${{ steps.check.outputs.continue == 'true' }}
      run: |
        result=$(cfn-lint -f checkstyle 2>&1) || true
        if echo "$result" | grep -q '<?xml'; then
          echo "$result" | reviewdog -f=checkstyle -name=cfn-lint -reporter=github-pr-review -filter-mode=nofilter -fail-level=any -level=info
        fi
