---
name: 'Cfn-lint'
description: 'Execute cfn-lint'

inputs:
  linters:
    description: 'List of all enabled linters'
    required: true
  ssh-key:
    description: 'ssh key'
    required: true
  github-token:
    description: 'github token'
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - name: Check if CFNLINT is enabled
      id: check
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        LINTERS: ${{ inputs.linters }}
      run: if echo "${LINTERS}" | grep CFNLINT &> /dev/null; then echo "continue=true" >> "${GITHUB_OUTPUT}"; else echo "continue=false" >> "${GITHUB_OUTPUT}"; fi

    # https://github.com/marketplace/actions/checkout
    - name: Checkout
      uses: actions/checkout@v6
      if: ${{ steps.check.outputs.continue == 'true' }}
      with:
        token: ${{ inputs.github-token }}
        ssh-key: ${{ inputs.ssh-key }}
        persist-credentials: false
        lfs: true
        submodules: recursive

    # https://github.com/marketplace/actions/cfn-lint-action
    - name: Setup cfn-lint
      uses: ScottBrenner/cfn-lint-action@v2
      if: ${{ steps.check.outputs.continue == 'true' }}

    - name: Run cfn-lint
      shell: bash
      if: ${{ steps.check.outputs.continue == 'true' }}
      run: cfn-lint
