---
name: 'Bandit'
description: 'Execute bandit'

inputs:
  linters:
    description: 'List of all enabled linters'
    required: true
  ssh-key:
    description: 'ssh key'
    required: true
  github_token:
    description: 'github token'
    required: true

runs:
  using: "composite"
  steps:
    - id: check
      shell: bash
      env:
        LINTERS: ${{ inputs.linters }}
      run: if echo "${LINTERS}" | grep BANDIT &> /dev/null; then echo "continue=true" >> "${GITHUB_OUTPUT}"; else echo "continue=false" >> "${GITHUB_OUTPUT}"; fi

    # https://github.com/marketplace/actions/checkout
    - name: Checkout
      uses: actions/checkout@v4
      if: ${{ steps.check.outputs.continue == 'true' }}
      with:
        ssh-key: ${{ inputs.ssh-key }}
        persist-credentials: true
        lfs: true
        submodules: recursive

    # https://github.com/marketplace/actions/bandit-security-linter
    - name: Bandit
      uses: tj-actions/bandit@v5
      if: ${{ steps.check.outputs.continue == 'true' }}
      with:
        targets: "."
        # https://github.com/PyCQA/bandit
        options: "-ll --ini .bandit --silent"
