#!/usr/bin/env bash

# Scan this repo's hand-maintained YAML for external `uses: org/repo@ref`
# GitHub Action references, resolve each to its latest upstream version, and
# (with --apply) rewrite the refs in place. Powers the weekly external-actions
# bump cron (issue #212).
#
# Usage:
#   bump-actions/bump-actions.sh                          # dry run: list available bumps
#   bump-actions/bump-actions.sh --apply                  # edit files in place
#   bump-actions/bump-actions.sh --apply --pr-body-file body.md
#
# Requires an authenticated `gh` on PATH. Rules:
#   - skip cloud-officer/* (our own actions; floating @v2 handles those) and ./ local refs;
#   - skip 40-char SHA pins and branch pins (e.g. @main) — only version tags are bumped;
#   - skip github-build-generated files (their refs are the generator's job);
#   - floating major tag (vN / N): bump only when the latest MAJOR increases,
#     keeping the floating form (e.g. v6 -> v7);
#   - exact pin (vX.Y / X.Y.Z): bump to the latest release tag when strictly newer.
#
# Set BUMP_SCAN_ROOT to scan a directory other than the git work tree (used by
# the test suite). The body runs only when executed directly, so the suite can
# source this file to unit-test the helpers below.

# ===========================================================================
# Helpers (pure / individually testable)
# ===========================================================================

function is_sha()            { [[ "$1" =~ ^[0-9a-f]{40}$ ]]; }
function is_floating_major() { [[ "$1" =~ ^v?[0-9]+$ ]]; }
function is_exact_semver()   { [[ "$1" =~ ^v?[0-9]+\.[0-9]+ ]]; }
function major_of()          { local v="${1#v}"; echo "${v%%.*}"; }
function esc_re()            { printf '%s' "$1" | sed 's/[.[\*^$/]/\\&/g'; }

# version_gt A B -> true when A is a strictly newer version than B, comparing
# with `sort -V` and ignoring a leading v (so 0.36.0 > v0.35.0, v0.10.0 > v0.9.1,
# and v0.35.0 == 0.35.0 -> not greater, avoiding cosmetic churn).
function version_gt()
{
  local a="${1#v}" b="${2#v}"
  [ "${a}" != "${b}" ] && [ "$(printf '%s\n%s\n' "${a}" "${b}" | sort -V | tail -1)" = "${a}" ]
}

# List candidate YAML files, skipping vendor dirs and github-build-generated
# files (first line `# github-build ...`, or an AUTO-GENERATED marker).
function target_files()
{
  find . \
    \( -path './.git' -o -path './node_modules' -o -path '*/node_modules' \
       -o -path '*/vendor' -o -path '*/dist' \) -prune -o \
    -type f \( -name '*.yml' -o -name '*.yaml' \) -print \
  | while IFS= read -r f; do
      if head -n1 "${f}" | grep -q '^# github-build' \
         || grep -q 'AUTO-GENERATED by github-build' "${f}"; then
        continue
      fi
      printf '%s\n' "${f}"
    done
}

# Emit unique external `org/repo[/subpath]@ref` references from the given files,
# excluding local (./...) and cloud-officer/* (case-insensitive) refs.
function extract_refs()
{
  grep -hoE "uses:[[:space:]]*[A-Za-z0-9_.-]+/[A-Za-z0-9_./-]+@[A-Za-z0-9_.-]+" "$@" 2>/dev/null \
    | sed -E 's/uses:[[:space:]]*//' \
    | grep -viE '^(\./|cloud-officer/)' \
    | sort -u
}

# Latest upstream version tag for org/repo: prefer the published release,
# falling back to the highest semver tag for repos that only tag.
function latest_version()
{
  local or="$1" tag
  tag="$(gh api "repos/${or}/releases/latest" --jq '.tag_name' 2>/dev/null || true)"
  if [ -z "${tag}" ] || [ "${tag}" = "null" ]; then
    tag="$(gh api "repos/${or}/tags?per_page=100" --jq '.[].name' 2>/dev/null \
            | grep -E '^v?[0-9]+(\.[0-9]+)*$' | sort -V | tail -1 || true)"
  fi
  printf '%s' "${tag}"
}

# Does org/repo publish the given tag (e.g. a floating "v7")? Direct single-ref
# lookup so it works regardless of how many tags the repo has (listing tags is
# paginated and can miss a floating major on repos with >100 tags).
function tag_exists()
{
  gh api "repos/$1/git/ref/tags/$2" --jq '.ref' >/dev/null 2>&1
}

# Resolve the new ref for a current ref, or empty when no bump applies.
# Echoes the new version (e.g. "v7" or "v0.10.0"); prints warnings to stderr.
function resolve_bump()
{
  local path="$1" ver="$2"
  local or new="" latest latest_major cur_major prefix candidate
  or="$(printf '%s' "${path}" | cut -d/ -f1-2)"

  is_sha "${ver}" && return 0

  latest="$(latest_version "${or}")"
  if [ -z "${latest}" ]; then
    echo "::warning::could not resolve latest version for ${or} (currently @${ver}); skipping" >&2
    return 0
  fi

  if is_floating_major "${ver}"; then
    latest_major="$(major_of "${latest}")"
    cur_major="$(major_of "${ver}")"
    [[ "${latest_major}" =~ ^[0-9]+$ ]] || return 0
    if [ "${latest_major}" -gt "${cur_major}" ]; then
      prefix=""; [[ "${ver}" == v* ]] && prefix="v"
      candidate="${prefix}${latest_major}"
      if tag_exists "${or}" "${candidate}"; then new="${candidate}"; else new="${latest}"; fi
    fi
  elif is_exact_semver "${ver}"; then
    version_gt "${latest}" "${ver}" && new="${latest}"
  else
    echo "::warning::${or}@${ver} is not a version tag (branch/unknown); skipping" >&2
  fi

  printf '%s' "${new}"
}

# ===========================================================================
# Main
# ===========================================================================

function main()
{
  set -euo pipefail

  local apply=false pr_body_file=""
  while [ $# -gt 0 ]; do
    case "$1" in
      --apply) apply=true ;;
      --pr-body-file) pr_body_file="${2:?--pr-body-file needs a path}"; shift ;;
      *) echo "::error::unknown argument: $1" >&2; return 2 ;;
    esac
    shift
  done

  cd "${BUMP_SCAN_ROOT:-$(git rev-parse --show-toplevel 2>/dev/null || pwd)}"

  local files
  mapfile -t files < <(target_files)
  if [ "${#files[@]}" -eq 0 ]; then
    echo "No YAML files to scan." >&2
    return 0
  fi

  # Parallel arrays describing each bump.
  local bump_repo=() bump_old=() bump_new=()
  local ref path ver new
  while IFS= read -r ref; do
    [ -n "${ref}" ] || continue
    path="${ref%@*}"
    ver="${ref##*@}"
    new="$(resolve_bump "${path}" "${ver}")"
    if [ -n "${new}" ]; then
      bump_repo+=("${path}"); bump_old+=("${ver}"); bump_new+=("${new}")
    fi
  done < <(extract_refs "${files[@]}")

  local count="${#bump_repo[@]}"
  if [ "${count}" -eq 0 ]; then
    echo "No external action bumps available."
    return 0
  fi

  local i
  for i in "${!bump_repo[@]}"; do
    printf 'BUMP\t%s\t%s -> %s\n' "${bump_repo[$i]}" "${bump_old[$i]}" "${bump_new[$i]}"
  done
  echo "${count} bump(s) available."

  # Apply: rewrite each ref in every file that carries it.
  if [ "${apply}" = true ]; then
    local path old pat f tmp
    for i in "${!bump_repo[@]}"; do
      path="${bump_repo[$i]}"; old="${bump_old[$i]}"; new="${bump_new[$i]}"
      pat="$(esc_re "${path}")@$(esc_re "${old}")"
      while IFS= read -r f; do
        tmp="$(mktemp)"
        # Match a uses: ref (optionally quoted) followed by EOL or a trailing
        # comment, preserving any closing quote/comment. Mirrors the grep below.
        sed -E "s#(uses:[[:space:]]*[\"']?)${pat}([\"']?([[:space:]].*)?)\$#\1${path}@${new}\2#" "${f}" > "${tmp}"
        if ! cmp -s "${f}" "${tmp}"; then mv "${tmp}" "${f}"; echo "updated ${f}: ${path}@${old} -> @${new}"; else rm -f "${tmp}"; fi
      done < <(grep -lE "uses:[[:space:]]*[\"']?${pat}([\"']|[[:space:]]|\$)" "${files[@]}" 2>/dev/null || true)
    done
  fi

  # PR body: table of bumps + truncated upstream release notes.
  if [ -n "${pr_body_file}" ]; then
    local or notes
    {
      echo "## Automated external action bumps"
      echo
      echo "Bumps external GitHub Action references to their latest upstream major/release."
      echo "Generated by \`bump-actions/bump-actions.sh\` (issue #212). Review the linked"
      echo "release notes for breaking changes before merging."
      echo
      echo "| Action | From | To |"
      echo "| --- | --- | --- |"
      for i in "${!bump_repo[@]}"; do
        printf '| %s | %s | %s |\n' "${bump_repo[$i]}" "${bump_old[$i]}" "${bump_new[$i]}"
      done
      echo
      echo "### Upstream release notes"
      for i in "${!bump_repo[@]}"; do
        path="${bump_repo[$i]}"; new="${bump_new[$i]}"
        or="$(printf '%s' "${path}" | cut -d/ -f1-2)"
        echo
        echo "#### ${path} ${new}"
        echo
        notes="$(gh release view "${new}" --repo "${or}" --json body --jq '.body' 2>/dev/null || true)"
        if [ -n "${notes}" ]; then
          printf '%s\n' "${notes}" | head -n 40
        else
          echo "_Release notes not available; see https://github.com/${or}/releases_"
        fi
      done
    } > "${pr_body_file}"
    echo "Wrote PR body to ${pr_body_file}"
  fi
  return 0
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  main "$@"
fi
