---
name: 'Semgrep'
description: 'Execute Semgrep security scanner'

inputs:
  linters:
    description: 'List of all enabled linters'
    required: true
  ssh-key:
    description: 'ssh key'
    required: true
  github_token:
    description: 'github token'
    required: true

runs:
  using: "composite"
  steps:
    - id: check
      shell: bash
      env:
        LINTERS: ${{ inputs.linters }}
      run: if echo "${LINTERS}" | grep SEMGREP &> /dev/null; then echo "continue=true" >> "${GITHUB_OUTPUT}"; else echo "continue=false" >> "${GITHUB_OUTPUT}"; fi

    # https://github.com/marketplace/actions/checkout
    - name: Checkout
      uses: actions/checkout@v4
      if: ${{ steps.check.outputs.continue == 'true' }}
      with:
        ssh-key: ${{ inputs.ssh-key }}
        persist-credentials: true
        lfs: true
        submodules: recursive

    # https://github.com/marketplace/actions/setup-python
    - name: Setup Python
      uses: actions/setup-python@v5
      if: ${{ steps.check.outputs.continue == 'true' }}
      with:
        python-version: '3.x'

    - name: Install Semgrep
      shell: bash
      if: ${{ steps.check.outputs.continue == 'true' }}
      run: pip install semgrep

    - name: Run Semgrep
      shell: bash
      if: ${{ steps.check.outputs.continue == 'true' }}
      run: semgrep scan --config=auto --severity=ERROR --sarif-output=semgrep.sarif .

    - name: Check for Semgrep findings
      shell: bash
      if: ${{ steps.check.outputs.continue == 'true' }}
      run: |
        if [ ! -f "semgrep.sarif" ]; then
          echo "No SARIF file found"
          exit 0
        fi

        FINDINGS_COUNT=$(jq '[.runs[].results[]] | length' semgrep.sarif)

        if [ "$FINDINGS_COUNT" -gt 0 ]; then
          exit 1
        fi

    # https://github.com/github/codeql-action
    - name: Upload SARIF to GitHub Security
      uses: github/codeql-action/upload-sarif@v4
      if: ${{ steps.check.outputs.continue == 'true' && always() }}
      continue-on-error: true
      with:
        sarif_file: semgrep.sarif
        category: semgrep
