---
name: 'Markdownlint'
description: 'Execute markdownlint'

inputs:
  linters:
    description: 'List of all enabled linters'
    required: true
  ssh-key:
    description: 'ssh key'
    required: true
  github_token:
    description: 'github token'
    required: true

runs:
  using: "composite"
  steps:
    - name: Check if MARKDOWNLINT is enabled
      id: check
      shell: bash
      run: if echo "${{ inputs.linters }}" | grep MARKDOWNLINT &> /dev/null; then echo "continue=true" >> "${GITHUB_OUTPUT}"; else echo "continue=false" >> "${GITHUB_OUTPUT}"; fi

    # https://github.com/marketplace/actions/checkout
    - name: Checkout
      uses: actions/checkout@v4
      if: ${{ steps.check.outputs.continue == 'true' }}
      with:
        ssh-key: ${{ inputs.ssh-key }}
        persist-credentials: true
        lfs: true
        submodules: recursive

    - name: Remove vendor, node_modules, Libraries
      shell: bash
      if: ${{ steps.check.outputs.continue == 'true' }}
      run: |
        grep path .gitmodules | grep -v scripts | awk '{ print $3 }' | xargs rm -rf || true
        find . -type d -name vendor -exec rm -rf {} \; || true
        find . -type d -name node_modules -exec rm -rf {} \; || true
        find . -type d -name Libraries -exec rm -rf {} \; || true

    # https://github.com/marketplace/actions/run-markdownlint-with-reviewdog
    - name: Run markdownlint with Reviewdog
      uses: reviewdog/action-markdownlint@v0
      if: ${{ steps.check.outputs.continue == 'true' }}
      with:
        fail_level: any
        filter_mode: nofilter
        github_token: ${{ inputs.github_token }}
        level: info
        # https://github.com/igorshubovych/markdownlint-cli
        markdownlint_flags: "."
        reporter: github-pr-review
        # reviewdog_flags:
