---
name: 'Markdownlint'
description: 'Execute markdownlint'

inputs:
  linters:
    description: 'List of all enabled linters'
    required: true
  ssh-key:
    description: 'ssh key'
    required: true
  github-token:
    description: 'github token'
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - name: Check if MARKDOWNLINT is enabled
      id: check
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        LINTERS: ${{ inputs.linters }}
      run: if echo "${LINTERS}" | grep MARKDOWNLINT &> /dev/null; then echo "continue=true" >> "${GITHUB_OUTPUT}"; else echo "continue=false" >> "${GITHUB_OUTPUT}"; fi

    # https://github.com/marketplace/actions/checkout
    - name: Checkout
      uses: actions/checkout@v6
      if: ${{ steps.check.outputs.continue == 'true' }}
      with:
        token: ${{ inputs.github-token }}
        ssh-key: ${{ inputs.ssh-key }}
        persist-credentials: true
        lfs: true
        submodules: recursive

    - name: Remove vendor, node_modules, Libraries
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      if: ${{ steps.check.outputs.continue == 'true' }}
      run: |
        grep path .gitmodules | grep -v scripts | awk '{ print $3 }' | xargs rm -rf || true
        find . -type d -name vendor -exec rm -rf {} \; || true
        find . -type d -name node_modules -exec rm -rf {} \; || true
        find . -type d -name Libraries -exec rm -rf {} \; || true

    # https://github.com/marketplace/actions/setup-reviewdog
    - name: Setup Reviewdog
      uses: reviewdog/action-setup@v1
      if: ${{ steps.check.outputs.continue == 'true' }}
      with:
        reviewdog_version: latest

    # https://github.com/marketplace/actions/setup-node-js-environment
    - name: Setup Node
      uses: actions/setup-node@v6
      if: ${{ steps.check.outputs.continue == 'true' }}
      with:
        token: ${{ inputs.github-token }}
        node-version: latest

    - name: Install markdownlint-cli2
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
      if: ${{ steps.check.outputs.continue == 'true' }}
      run: |
        npm install -g markdownlint-cli2

    - name: Run markdownlint
      shell: bash
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ inputs.github-token }}
      if: ${{ steps.check.outputs.continue == 'true' }}
      run: |
        markdownlint-cli2 "**/*.md" 2>&1 | reviewdog -efm="%f:%l:%c %m" -efm="%f:%l %m" -name="markdownlint" -reporter="github-pr-review" -filter-mode="nofilter" -fail-level="any" -level="info"
