---
name: 'Prepare variables'
description: 'Prepare variables for all other parallel jobs.'

inputs:
  ssh-key:
    description: 'ssh key'
    required: true

runs:
  using: "composite"
  steps:
    # https://github.com/marketplace/actions/checkout
    - uses: actions/checkout@v3
      with:
        ssh-key: ${{ inputs.ssh-key }}
        persist-credentials: true
        lfs: true
        submodules: recursive

    - shell: bash
      run: echo "${{ github.action_path }}" >> ${GITHUB_PATH}

    - id: variables
      shell: bash
      run: variables.sh
