---
name: 'Golangci-lint'
description: 'Execute golangci-lint'

inputs:
  linters:
    description: 'List of all enabled linters'
    required: true
  ssh-key:
    description: 'ssh key'
    required: true
  github-token:
    description: 'github token'
    required: false
    default: ${{ github.token }}

runs:
  using: "composite"
  steps:
    - name: Check if GOLANGCI is enabled
      id: check
      shell: bash
      env:
        GITHUB_TOKEN: ${{ inputs.github-token }}
        LINTERS: ${{ inputs.linters }}
      run: if echo "${LINTERS}" | grep GOLANGCI &> /dev/null; then echo "continue=true" >> "${GITHUB_OUTPUT}"; else echo "continue=false" >> "${GITHUB_OUTPUT}"; fi

    # https://github.com/marketplace/actions/checkout
    - name: Checkout
      uses: actions/checkout@v6
      if: ${{ steps.check.outputs.continue == 'true' }}
      with:
        token: ${{ inputs.github-token }}
        ssh-key: ${{ inputs.ssh-key }}
        persist-credentials: false
        lfs: true
        submodules: recursive

    # https://github.com/marketplace/actions/run-golangci-lint-with-reviewdog
    - name: Golangci-lint
      uses: reviewdog/action-golangci-lint@v2
      if: ${{ steps.check.outputs.continue == 'true' }}
      with:
        fail_level: error
        filter_mode: nofilter
        github_token: ${{ inputs.github-token }}
        # https://github.com/golangci/golangci-lint
        golangci_lint_flags: ""
        level: info
        reporter: github-pr-review
        # reviewdog_flags:
        tool_name: golangci
        workdir: "."
